### ISSUE TITLE
Sparks masternode setup

### ISSUE THREAD

**Issue by funmbiokoya** [sparkscrypto/Sparks#6]
I am at step 7. Everytime I type “masternode outputs”, I get empty brackets as the response. No characters, just brackets. I don’t know if that’s normal or if something is wrong.

Also, is the response I get after sending “masternode outputs” supposed to replace “collateral_output_txid” in “masternode.conf” at step 9?

https://github.com/sparkscrypto/Sparks/blob/master/How%20to%20create%20masternode.pdf

**Comment by m0r4k** [comment]
You need a transfer of exactly 1000 SPKs to your masternode wallet.
After this minimum 6 confirmations
Then on the masternode 

```{r, engine='bash', count_lines}
shell:~/.Sparks$ Sparks-cli masternode outputs 
```
To view if the transactions did come you can do;

```{r, engine='bash', count_lines}
shell:~/.Sparks$ Sparks-cli listtransaction

--> output would be something like:

[
  {
    "account": "youraccount",
    "address": "YOUR ADDRESS",
    "category": "receive",
    "amount": 1000.00000000,
    "label": "YOUR LABEL",
    "vout": 1,
    "confirmations": 79,
    "bcconfirmations": 79,
    "blockhash": "HASH",
    "blockindex": 1,
    "blocktime": 1519925956,
    "txid": "TXID",
    "walletconflicts": [
    ],
    "time": 1519925826,
    "timereceived": 1519925826,
    "bip125-replaceable": "no"
  }
]
```
I did try this about 100000 times, suddenly after 3 days I found out that the
transfer has to be exactly 1000 -> 1000,002 also worked but 1002 or 2000 did not.

After you've transfered your 1000 SPKs you can send more, this doesn't change 
the STATUS of Masternode. 

**BTW** you should also lock these 1000 Spks that you don't spent them accidentaly!


```{r, engine='bash', count_lines}
shell:~/.Sparks$ Sparks-cli lockunspent false "[{\"txid\":\"TXID\",\"vout\":NUM_WITHOUT_QUOTES}]"
```

**Comment by lobeznosp3** [comment]
Here there is a new Guide to setup a Sparks Masternode:

[Sparks MN Setup Ubuntu 16.04 and Windows Cold Wallet v1.1.pdf](https://github.com/sparkscrypto/Sparks/files/1784167/Sparks.MN.Setup.Ubuntu.16.04.and.Windows.Cold.Wallet.v1.1.pdf)

**Comment by JaimeLopes** [comment]
You can transfer the coins to yourself if you have already transferred them to your wallet. I tried to send out the extra but ended up with less than 1000... transferred the exact amount back to make 1000 but was still getting blank `masternode outputs` result. So then I just transferred 1000 to myself and viola it worked, MN has been up for 4 days with around 9SPK coming in every ~20Hrs...

**Comment by sukanda18** [comment]
hi  help me  I want to load   new Guide to setup a Sparks Masternode:


I can't load

**Comment by casadocaio** [comment]
Hi there, is there a way to set it up with windows?

**Comment by lobeznosp3** [comment]
You can check in the new website: https://www.sparkscoin.io or discord channel: https://discord.gg/7DEsdBc
